# Generated by Django 4.1.5 on 2023-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='options',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1, verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название Продукта'),
        ),
    ]
