# Generated by Django 4.1.5 on 2023-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(default='', max_length=20, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.CharField(default='0', max_length=100, verbose_name='Сумма'),
        ),
    ]
