# Generated by Django 4.1.5 on 2023-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_products_slug_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.CharField(default='', max_length=250, verbose_name='Доставка'),
        ),
    ]
